version: "3.8"

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=api-gateway
        - PORT=4005
    restart: "no"
    ports:
      - "4005:4005"
    environment:
      - API_GATEWAY_PORT=4005
      - PORT=4005
      - IMAGE_PROCESSING_HOST=http://image-processing:4006
      - IMAGE_PROCESSING_PORT=4006
      - IMAGE_CROPPING_HOST=http://image-cropping:4007
      - IMAGE_CROPPING_PORT=4007
    depends_on:
      - image-cropping
      - image-processing
    healthcheck:
      test: curl -f http://image-cropping:4005/health || exit 1
    networks:
      - app-network

  image-processing:
    container_name: image-processing
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=image-processing
        - PORT=4006
    restart: "no"

    environment:
      - IMAGE_PROCESSING_PORT=4006
      - PORT=4006
    networks:
      - app-network

  image-cropping:
    container_name: image-cropping
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP=cropping
        - PORT=4007
    restart: "no"
    ports:
      - "4007:4007"
    environment:
      - IMAGE_CROPPING_PORT=4007
      - PORT=4007

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
#TODO: Exposed microservice ports
